version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "developerasun"
    labels:
      - "dependencies"
