# see here for more details: https://golangci-lint.run/usage/configuration/

run:
  skip-files:
    - ".*\\.service\\.go$" # avoid zap logger error check

# linters and linters-settings is applied to core directory
linters:
  disable:
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    ignore: fmt:.*
    disable-default-exclusions: true
