// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CreateEnvBotConfig(arg1:config.ModelEnvBot):Promise<void>;

export function InitEnvBot():Promise<boolean>;
