// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CreateEmailUser_(arg1:string,arg2:string):Promise<config.OWLLY_RESPONSE>;

export function InitEnvBot():Promise<boolean>;

export function ReadEmailUser_(arg1:string,arg2:string):Promise<config.OWLLY_RESPONSE>;
