// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEmailUser_(arg1, arg2) {
  return window['go']['main']['Owlly']['CreateEmailUser_'](arg1, arg2);
}

export function InitEnvBot() {
  return window['go']['main']['Owlly']['InitEnvBot']();
}

export function ReadEmailUser_(arg1, arg2) {
  return window['go']['main']['Owlly']['ReadEmailUser_'](arg1, arg2);
}
