// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitEnvBot() {
  return window['go']['main']['Owlly']['InitEnvBot']();
}
