name: auto label

on:
  pull_request:

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'breaking/')
        with:
          labels: |
            enhancement
            major

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'feature/')
        with:
          labels: |
            enhancement
            minor

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'test/')
        with:
          labels: |
            test
            patch

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'bugfix/')
        with:
          labels: |
            bug
            patch

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'refactor/')
        with:
          labels: |
            refactor
            patch

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'docs/')
        with:
          labels: documentation
