---
name: lint and release

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    strategy:
      matrix:
        go: [1.19]
        os: [macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}

    steps:
      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: code cloning
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

  release:
    name: auto release
    runs-on: ubuntu-latest
    steps:
      - name: auto release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
