name: auto-formatter

on:
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        go: [1.19]
        os: [macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: repo cloning
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

  format:
    name: golines formatting
    runs-on: "ubuntu-latest"
    steps:
      - name: install
        run: go install github.com/segmentio/golines@latest

      - name: format
        run: golines -w .

      - name: done message
        run: echo "Lines are formatted."
